spring:
  application:
    name: user-identity

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${KC_CLIENT_ID}
            client-secret: ${KC_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope: openid,profile,email
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
        provider:
          keycloak:
            issuer-uri: ${KC_URL}
            user-name-attribute: preferred_username

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
  use-management-port: true

management:
  server:
    port: 9080  # Management port
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,openapi,swagger-ui"
